### ISSUE TITLE
How to serialize values which are provided JsonInclude.Include.NON_NULL at class level

### ISSUE THREAD

**Issue by SawyerFord** [FasterXML/jackson-docs#12]
Currently my application has a class which is as below

     @JsonInclude(JsonInclude.Include.NON_NULL)
      public class Employee {
         Department department;
         String firstName;
         String lastName;
         String address;
         String phoneNumber;
      }
I am capturing the employee object inside the logs where I am converting the object into JSON. I am able to convert the object to JSON but the null values do not get into the JSON.

I have tried the below

     objectMapper.setSerializationInclusion(JsonInclude.Include.ALWAYS);
     generator.setCodec(objectMapper);
     generator.writeObjectField(fieldName, argument);

But not able to get the null values of the fields in JSON. How do I get them?

**Comment by cowtowncoder** [comment]
This is not a question forum.
