### ISSUE TITLE
Dead link on Jackson performance

### ISSUE THREAD

**Issue by franzwong** [FasterXML/jackson-docs#13]
I found most of the links (related to wiki.fasterxml.com) on this page are dead.
https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance

**Comment by cowtowncoder** [comment]
Thanks, yes. FasterXML wiki is down and probably gone. Need to see if I can find actually presentation somewhere.

**Comment by cowtowncoder** [comment]
I only saw one link, fixed that one.
