### ISSUE TITLE
Update Jackson Mixin description

### ISSUE THREAD

**Issue by udalrich** [FasterXML/jackson-docs#14]
This page, https://github.com/FasterXML/jackson-docs/wiki/JacksonMixInAnnotations, says to use

    objectMapper.getSerializationConfig().addMixInAnnotations(Rectangle.class, MixIn.class);
    objectMapper.getDeserializationConfig().addMixInAnnotations(Rectangle.class, MixIn.class);

However, `objectMapper.get*Config()` returns an immutable object.  The documentation also implies that there is one set of mixins for serialization and one for deserialization.  This does not appear to be the case anymore.

**Comment by cowtowncoder** [comment]
@udalrich Thanks, that sounds like out of date. I'll have a look.

**Comment by cowtowncoder** [comment]
Updated. I also think that Wikis are user-editable; or if not, I should be able to grant access for anyone who wants to contribute.
