### ISSUE TITLE
JacksonInFiveMinutes page content is missed

### ISSUE THREAD

**Issue by devsnice** [FasterXML/jackson-docs#20]
Hey, I was looking for some explaining of how jackson works inside and found out that this page is empty.

https://github.com/FasterXML/jackson-docs/wiki/Jackson-Tutorial

any plans for restore it? Thanks

**Comment by cowtowncoder** [comment]
Restore? I don't think there has been content on this page, ever.

Closest thing Jackson project itself has is probably README of jackson-databind:

https://github.com/FasterXML/jackson-databind/

although there are now better tutorials elsewhere; some are linked to from README of this repo.
