### ISSUE TITLE
Main Jackson README is beind on latest versions

### ISSUE THREAD

**Issue by mjustin** [FasterXML/jackson-docs#25]
Since https://github.com/FasterXML/jackson doesn't appear to allow issues to be reported against it…

The main [README](https://github.com/FasterXML/jackson/blob/master/README.md) for the Jackson project is behind on what the latest version is.  As of this writing, 2.15.2 is the latest version deployed to Maven Central.  However, the README is behind the times in a few places, stating that 2.13.4 as being the latest released version:

> ## What is New?
> 
> * Nov 2, 2022: AdaLogics Security Audit for Jackson released -- see Document/Reports
> * Oct 28, 2022: Jackson 2.14 Release Candidate 3 (2.14.0-rc3) released; 2.14.0 itself soon to be released!
> * Sep 3, 2022: Jackson 2.13.4 patch released
> * Sep 30, 2021: Jackson 2.13.0 (new stable) released
> * Oct 1, 2020: Jackson participates in [Hacktoberfest2020](https://hacktoberfest.digitalocean.com/) and we have a [Jackson/Hacktoberfest](https://github.com/FasterXML/Hacktoberfest2020) repo too!
> * Oct 9, 2020: Added [Contributing](CONTRIBUTING.md)

> ## Actively developed versions
> 
> Jackson suite has two major versions: 1.x is deprecated and no versions are released;
> 2.x is the actively developed version.
> These two major versions use different Java packages and Maven artifact ids, so they are not mutually compatible, but can peacefully co-exist: a project can depend on both Jackson 1.x and 2.x, without conflicts.
> This is by design and was chosen as the strategy to allow smoother migration from 1.x to 2.x.
> 
> The latest stable versions from these branches are:
> 
> * [2.13.4](../../wiki/Jackson-Release-2.13), released on 3-Sept-2022
>     * [2.12.7](../../wiki/Jackson-Release-2.12) is the latest patch from previous stable branch
> * [1.9.13](../../wiki/JacksonRelease1.9), released 14-Jul-2013

> ### Active developed Jackson 2.x branches
> 
> Currently Jackson 2.x repositories have following actively developed branches:
> 
> * `2.14`: next minor version being developed (as of May 2022)
> * `2.13`: current stable, actively maintained branch from which one more patch release is possible
> * `2.12`: previous stable branch, only micro-patches likely to be released
> * `master`: next major version, 3.0. Still changing rapidly

Ideally, the README.md file should be brought up to date, and processes would be put in place to prevent it falling back out of date as new versions are released.

**Comment by cowtowncoder** [comment]
Thanks. PRs are always welcome, but I'll make some minor tweaks there.

I am not sure I have much interest in spending time on automation here since auto-generation tends to lead to lots of noise and questionable content/value ratio.
But will try to make manual updates on new minor releases at least, as part of process of releasing new versions (for which I actively do update release notes).

**Comment by cowtowncoder** [comment]
@mjustin Oh this is embarrassing: I had made a few updates, but to a .... branch. Meant to only be used for staging announcement of security audit doc.

But.

Had forgotten to actually merge the branch.

So while things were not fully up to date, they were further out of date than I thought.

Thank you for reporting this.
