### ISSUE TITLE
http://wiki.fasterxml.com/ isn't accessible 

### ISSUE THREAD

**Issue by herau** [FasterXML/jackson-docs#4]
This site can’t be reached

**Comment by cowtowncoder** [comment]
Yes, a known problem. No ETA for getting back unfortunately.

**Comment by patrick-webs** [comment]
https://github.com/FasterXML still links to the dead site http://fasterxml.com/ - can this be updated to reflect Jackson currently doesn't have a website? Just spent 10 minutes searching trying to figure out why all the links to the wiki are dead, and the only references I found were a google group post and finally this issue - there's still a lot of broken links out there!

**Comment by schmod** [comment]
Can we move the remaining docs on fasterxml.com to github pages?

**Comment by cowtowncoder** [comment]
At this moment the site is unaccessible to me as well. I don't have ssh keys for it, even when up, so I rely on another team member for that, and he's on vacation.

But once we get access, we could get a raw dump: however, it uses different markup, and links are likely to be broken. If someone was eager and willing to help maybe these could be converted and cleaned up; I do not have time for that myself unfortunately. But I can help with accessibility... once I get some access myself.

@patrick-webs PRs welcome.

**Comment by patrick-webs** [comment]
@cowtowncoder https://github.com/FasterXML is the organization homepage, I don't think a PR is possible for this. Someone with access to the settings would need to go in and change it on github's website.

Please post any information here if there's a raw dump of the old wiki available! I may take a stab at converting the markup to markdown.

**Comment by cowtowncoder** [comment]
@patrick-webs ah yes you are right. I'll remove it.
